### ISSUE TITLE
schema with format overwrites minimum and maximum values

### ISSUE THREAD

**Issue by Shockolate** [mikunn/openapi-schema-to-json-schema#32]
If  a valid `format` is given, it overrides any given `minimum` and `maximum` values.

Consider:
```yaml
    TestObject:
      type: object
      properties:
        overridingInt:
          type: integer
          format: int32
          minimum: 0
          maximum: 10
        overridingFloat:
          type: number
          format: float
          minimum: -5
          maximum: 10
```

results in:
```json
{
  "type": "object",
  "properties": {
    "overridingInt": {
      "type": "integer",
      "format": "int32",
      "minimum": -2147483648,
      "maximum": 2147483647
    },
    "overridingFloat": {
      "type": "number",
      "format": "float",
      "minimum": -3.402823669209385e+38,
      "maximum": 3.402823669209385e+38
    }
  },
  "$schema": "http://json-schema.org/draft-04/schema#"
}
```
